import { defaultPersonalRulesDir, rulesSubdir } from "../paths.js";

export function personalRulesDirPath(): string {
  return rulesSubdir(defaultPersonalRulesDir());
}

export function renderCreateRulePrompt(options: { seed?: string } = {}): string {
  const rulesDir = personalRulesDirPath();
  const lines = [
    "# ai-rules: create a personal rule",
    "",
    "Conduct a rule-creation interview in this session. Ask **one question at a time**.",
    "Do not write the file until the user confirms the preview.",
    "",
    "## Question format",
    "For steps with fixed choices, present a **numbered option list** (not prose-only).",
    "The user may reply with the option number or label.",
    "Always include **Other (type your own)** when the preset list might not fit.",
    "For optional steps, include **Skip / use default**.",
    "Do not ask multiple interview questions in one message.",
    "",
    `## Save location`,
    `Write the finished rule to: \`${rulesDir}/<id>.md\``,
    "Create the directory if it does not exist.",
    "",
    "## Required file format",
    "Markdown with YAML frontmatter and these sections: Trigger, Rule, Prefer, Rationale, Example.",
    "",
    "```markdown",
    "---",
    "id: example.rule-id",
    "status: active",
    "layer: personal",
    "severity: medium",
    "scope:",
    "  languages: []",
    "  frameworks: []",
    "  globs: [\"**/*\"]",
    "  taskKinds: [feature, refactor]",
    "triggers:",
    "  keywords: [keyword1, keyword2]",
    "conflictsWith: []",
    "includeExample: never",
    "---",
    "",
    "## Trigger",
    "When ...",
    "",
    "## Rule",
    "...",
    "",
    "## Prefer",
    "...",
    "",
    "## Rationale",
    "...",
    "",
    "## Example",
    "",
    "```",
    "",
    "Fixed values: `layer: personal`, `status: active`. Use `includeExample: when-needed` only if Example is non-empty.",
    "",
    "## Interview (in order)",
    "",
    "### 1. Rule intent (freeform)",
    "What should the agent avoid or always do?",
    "",
    "### 2. Preferred behavior (freeform)",
    "What should it do instead?",
    "",
    "### 3. Trigger (freeform)",
    "When does this apply? (plain language for the Trigger section)",
    "",
    "### 4. Rationale (freeform, skippable)",
    "Why does this matter? Infer briefly if the user skips.",
    "",
    "### 5. File path patterns (MCQ)",
    "Which files should this rule apply to?",
    "1. Everywhere — `[\"**/*\"]`",
    "2. TypeScript/JavaScript — `[\"**/*.{ts,tsx,js,jsx}\"]`",
    "3. Frontend components — `[\"**/*.{tsx,jsx,vue,svelte}\"]`",
    "4. Backend/API — `[\"**/api/**\", \"**/routes/**\", \"**/server/**\"]`",
    "5. Tests only — `[\"**/*.{test,spec}.{ts,tsx,js,jsx}\"]`",
    "6. Other (type your own glob patterns)",
    "7. Skip / use default — `[\"**/*\"]`",
    "",
    "### 6. Languages and frameworks (MCQ, optional)",
    "Any language or framework scope?",
    "1. None — leave empty",
    "2. TypeScript",
    "3. JavaScript",
    "4. React",
    "5. Node.js",
    "6. Python",
    "7. Other (type comma-separated languages/frameworks)",
    "8. Skip / use default — none",
    "",
    "### 7. Task types (MCQ, multi-select OK)",
    "When should this rule surface?",
    "1. Feature + refactor (default)",
    "2. Feature only",
    "3. Fix / bugfix",
    "4. Refactor only",
    "5. Test",
    "6. Docs",
    "7. Review",
    "8. Chore",
    "9. All task types",
    "10. Other (type comma-separated: feature, fix, refactor, test, docs, review, chore)",
    "",
    "### 8. Trigger keywords (freeform)",
    "Which keywords in task text should surface this rule? Suggest 2–5 from the rule if obvious.",
    "",
    "### 9. Severity (MCQ)",
    "How strict is this rule?",
    "1. Low — preference, soft guidance",
    "2. Medium — standard rule (default)",
    "3. High — must not violate",
    "",
    "### 10. Rule id (MCQ + suggestion)",
    "Suggest an id from the rule (lowercase, dots or hyphens). Present your suggestion as option 1.",
    "1. `<your-suggested-id>` (Recommended)",
    "2. Other (type your own id slug)",
    "",
    "### 11. Example (MCQ, optional)",
    "Include a bad vs good example in the rule file?",
    "1. No — skip Example section (`includeExample: never`)",
    "2. Yes — I'll ask for bad/good snippets next",
    "3. Skip / infer from context if enough detail exists",
    "",
    "Skip or combine questions when the user already answered them. If a seed is provided below, use it and only ask what is still missing.",
    "",
    "## When finished",
    "1. Show the full Markdown preview.",
    "2. Ask with numbered options:",
    "   1. Save",
    "   2. Edit (say what to change)",
    "   3. Cancel",
    "3. On Save: write exactly one file to the save location. If `<id>.md` exists, ask before overwriting.",
    "4. Confirm the saved path and suggest testing with: `ai-rules debug select \"example task matching this rule\"`.",
  ];

  if (options.seed?.trim()) {
    lines.push("", "## Seed from user", options.seed.trim());
  }

  return lines.join("\n");
}

export function renderOpenCodeCreateRuleCommand(): string {
  return ["---", "description: Interview and create a personal ai-rules rule", "---", "", renderCreateRulePrompt(), "", "## Seed from user", "$ARGUMENTS", ""].join(
    "\n",
  );
}
