import { defaultPersonalRulesDir, rulesSubdir } from "../paths.js";

export function personalRulesDirPath(): string {
  return rulesSubdir(defaultPersonalRulesDir());
}

export function renderCreateRulePrompt(options: { seed?: string } = {}): string {
  const rulesDir = personalRulesDirPath();
  const lines = [
    "# ai-rules: create a personal rule",
    "",
    "Conduct a rule-creation interview in this session. Ask **one question at a time**.",
    "Do not write the file until the user confirms the preview.",
    "",
    "## Question format",
    "**Every interview step is MCQ.** Never ask a prose-only question.",
    "Use the built-in **`question` tool** for each step — **one question per tool call**. Do not dump numbered lists in chat as the only interface.",
    "",
    "Call `question` with a single entry in `questions`:",
    "- `header`: short step label (max 30 chars, e.g. `Rule intent`)",
    "- `question`: the full question text for this step",
    "- `options`: `{ label, description? }[]` from the step below (adapt option 1 when a seed or prior answer fits better)",
    "- Always include **Other (type your own)** as the last option",
    "- Include **Skip / use default** or **Infer from context** where noted below",
    "- Set `multiple: true` only for step 7 (task types)",
    "",
    "Wait for the tool result before the next step. Custom text entry is available when the user picks Other.",
    "Do not ask multiple interview questions in one message.",
    "",
    `## Save location`,
    `Write the finished rule to: \`${rulesDir}/<id>.md\``,
    "Create the directory if it does not exist.",
    "",
    "## Required file format",
    "Markdown with YAML frontmatter and these sections: Trigger, Rule, Prefer, Rationale, Example.",
    "",
    "```markdown",
    "---",
    "id: example.rule-id",
    "status: active",
    "layer: personal",
    "severity: medium",
    "scope:",
    "  languages: []",
    "  frameworks: []",
    "  globs: [\"**/*\"]",
    "  taskKinds: [feature, refactor]",
    "triggers:",
    "  keywords: [keyword1, keyword2]",
    "conflictsWith: []",
    "includeExample: never",
    "---",
    "",
    "## Trigger",
    "When ...",
    "",
    "## Rule",
    "...",
    "",
    "## Prefer",
    "...",
    "",
    "## Rationale",
    "...",
    "",
    "## Example",
    "",
    "```",
    "",
    "Fixed values: `layer: personal`, `status: active`. Use `includeExample: when-needed` only if Example is non-empty.",
    "",
    "## Interview (in order)",
    "",
    "### 1. Rule intent (MCQ)",
    "What should the agent avoid or always do?",
    "1. Use seed / prior answer as the rule (Recommended when seed is provided)",
    "2. Avoid calling fetch, axios, or IO directly inside UI components",
    "3. Keep diffs minimal — no unrelated refactors",
    "4. Never commit secrets, tokens, or credentials",
    "5. Always match existing project patterns — do not invent new ones",
    "6. Always add or update tests for behavior changes",
    "7. Other (type your own rule intent)",
    "",
    "### 2. Preferred behavior (MCQ)",
    "What should the agent do instead?",
    "1. Extract logic into a custom hook",
    "2. Use a service module or API layer",
    "3. Use server components, loaders, or route handlers",
    "4. Use an established data library (React Query, SWR, etc.)",
    "5. Keep components presentational — pass data via props",
    "6. Other (type your preferred approach)",
    "",
    "### 3. Trigger (MCQ)",
    "When does this rule apply? (plain language for Trigger section)",
    "1. When adding or changing feature code in scoped files",
    "2. When fixing bugs in scoped files",
    "3. When refactoring scoped files",
    "4. When reviewing PRs that touch scoped files",
    "5. Whenever working in scoped file patterns (broad)",
    "6. Other (describe in one sentence)",
    "",
    "### 4. Rationale (MCQ)",
    "Why does this matter?",
    "1. Infer briefly from context (Recommended)",
    "2. Testability — easier to unit test without IO in UI",
    "3. Separation of concerns — UI vs data fetching",
    "4. Reuse — share data logic across components",
    "5. Consistency — one pattern across the codebase",
    "6. Other (one sentence)",
    "",
    "### 5. File path patterns (MCQ)",
    "Which files should this rule apply to?",
    "1. Everywhere — `[\"**/*\"]`",
    "2. TypeScript/JavaScript — `[\"**/*.{ts,tsx,js,jsx}\"]`",
    "3. Frontend components — `[\"**/*.{tsx,jsx,vue,svelte}\"]`",
    "4. Backend/API — `[\"**/api/**\", \"**/routes/**\", \"**/server/**\"]`",
    "5. Tests only — `[\"**/*.{test,spec}.{ts,tsx,js,jsx}\"]`",
    "6. Other (type your own glob patterns)",
    "7. Skip / use default — `[\"**/*\"]`",
    "",
    "### 6. Languages and frameworks (MCQ, optional)",
    "Any language or framework scope?",
    "1. None — leave empty",
    "2. TypeScript",
    "3. JavaScript",
    "4. React",
    "5. Node.js",
    "6. Python",
    "7. Other (type comma-separated languages/frameworks)",
    "8. Skip / use default — none",
    "",
    "### 7. Task types (MCQ, multi-select OK)",
    "When should this rule surface?",
    "1. Feature + refactor (default)",
    "2. Feature only",
    "3. Fix / bugfix",
    "4. Refactor only",
    "5. Test",
    "6. Docs",
    "7. Review",
    "8. Chore",
    "9. All task types",
    "10. Other (type comma-separated: feature, fix, refactor, test, docs, review, chore)",
    "",
    "### 8. Trigger keywords (MCQ)",
    "Which keywords should surface this rule in task text?",
    "1. Use your suggested keywords from the rule (Recommended — list 2–5 in the option label)",
    "2. fetch, api, data, component",
    "3. react, hook, component, refactor",
    "4. test, mock, fixture",
    "5. Other (type comma-separated keywords)",
    "6. Skip / infer from rule text",
    "",
    "### 9. Severity (MCQ)",
    "How strict is this rule?",
    "1. Low — preference, soft guidance",
    "2. Medium — standard rule (default)",
    "3. High — must not violate",
    "",
    "### 10. Rule id (MCQ + suggestion)",
    "Suggest an id from the rule (lowercase, dots or hyphens). Present your suggestion as option 1.",
    "1. `<your-suggested-id>` (Recommended)",
    "2. Other (type your own id slug)",
    "",
    "### 11. Example (MCQ, optional)",
    "Include a bad vs good example in the rule file?",
    "1. No — skip Example section (`includeExample: never`)",
    "2. Yes — I'll ask for bad/good snippets next",
    "3. Skip / infer from context if enough detail exists",
    "",
    "Skip or combine questions when the user already answered them. If a seed is provided below, use it and only ask what is still missing.",
    "",
    "## When finished",
    "1. Show the full Markdown preview.",
    "2. Use the `question` tool: Save / Edit (say what to change) / Cancel.",
    "3. On Save: write exactly one file to the save location. If `<id>.md` exists, ask before overwriting.",
    "4. Confirm the saved path and suggest testing with: `ai-rules debug select \"example task matching this rule\"`.",
  ];

  if (options.seed?.trim()) {
    lines.push("", "## Seed from user", options.seed.trim());
  }

  return lines.join("\n");
}

export function renderOpenCodeCreateRuleCommand(): string {
  return ["---", "description: Interview and create a personal ai-rules rule", "---", "", renderCreateRulePrompt(), "", "## Seed from user", "$ARGUMENTS", ""].join(
    "\n",
  );
}
